### PR TITLE
Added visualizer module.

### PR DESCRIPTION
**Pull request by davidrpugh**
PR for adding a `Visualizer` class to the `pyam` for efficiently plotting functions of the equilibrium.

### CODE REVIEW

**Comment by davidrpugh** [comment]
@crisla and @Falter89 

How are you currently calculating the moments of the distributions of model predicted wages and profits, etc? I would have thought that this information would be useful for estimation. Maybe not.

If you think it would be useful, I could add methods for generating random samples from the model predicted equilibrium distributions. These method could then be used for some kind of simulated method of moments estimation.

**Comment by Falter89** [comment]
Hi David,

no, we are not calculating the moments of the distributions, but in general I think it’s a useful feature to have. Actually we are NOT matching DISTRIBUTIONS of wages and profits, but the CORRELATION with firm size (theta). In general, it’s probably useful to see distributions of the factor payments if needed, but it would be really useful to easily get the correlations between variables too. 

Best,
Julia

Am 23.07.2015 um 10:22 schrieb David R. Pugh notifications@github.com:

**Comment by davidrpugh** [comment]
@Falter89 

I have added examples of how to plot and compute the correlations using the solution output. See the `examples/positive-assortative-matching.ipynb` notebook.

**Comment by Falter89** [comment]
Yes, that's exactly what we were doing in the code before. Thanks!!

I tried to understand the way to compute the distribution for wages and profits, but I'm not sure I fully understand what the code is doing. What is should be doing might differ depending on whether we look at wages or profits though:

For profits: We need to use the pdf of theta, i.e. we need to know how many firms of type y employing workers of type x are there, then sort this by profit this gives us the pdf(profit). The cdf then follows easily. Is this what is happening in the code? I'm not sure if you're not simply sorting the data or if you are indeed using the pdf of theta again. 

For Wage: Here there are two distributions of interest: A) The distributions of average wage firms pay B) the wage distributions in the standard sense of how many workers get a certain wage

A) would be similar to how to get the profit distribution because the units are number of firms with a certain avg. wage, i.e. use pdf_theta again, sort by wage and done
B) here we need to multiply the number of firms of each match with how many workers they employ, i.e. pdf_theta \* theta, then sort by the wage and get the pdf from this. This might be quite different from the distribution in A). Users of this code might be interested in both things though.

**Comment by davidrpugh** [comment]
@Falter89 

The code I wrote was doing something different (and I think wrong).  I have now fixed things up along the lines suggested above. Take a look and let me know what you think. I am worried that I might not be normalizing the pdfs properly (so that they integrate to one).

**Comment by Falter89** [comment]
I think the distributions are right now. But when you mention the scaling, I just remembered another adjustment Cristina and I introduced. In the current notebook the distributions of x and y both integrate to 1. In reality there are a lot more x's than y's out there, so we scaled the cdf of x by a number approx= to the avg number of workers per firm. In the end we decided not to estimate this parameter, but just assumed it. I guess in theory this could also be estimated to help to get the firm size scaled correctly. Alternatively I think one could also change the interpretation of what theta means, i.e. it would be similar to a share of the total work force. If the mass of x = 1 as assumed now, I think it should be true that the sum (theta_pdf_theta_total number of firms) over all pairs = 1. To get the firm size that is comparable to the data one would need to multiply it by how many workers there are in total. Note that there is also an adjustment for the mass of firms in there. Not entirely sure this is error-free though.

Regarding the scaling of the pdf I'm also not sure what the correct units should be for this. Ideally it could be directly interpreted as number of firms or workers, but I'm not sure this works. Otherwise maybe just divide by the sum like it's now done for the cdf. Then the cumsum(pdf) = cdf and the cdf doesn't need to be rescaled anymore.  Actually the scaling of the pdf probably also matters and what I said above about scaling the distributions. Maybe we need to scale it so that is sums to 1 in order to ensure the total number of workers and firms is still correct.

**Comment by davidrpugh** [comment]
@crisla and @Falter89 

I have added an interactive widget to the notebook that allows you to toggle the model parameters and see how the model solution changes.  The solver makes use of a hot start when re-solving the model for new parameters.  Let me know how you get on using it.

**Comment by davidrpugh** [comment]
@Falter89 

OK, I have fixed the normalization and added support for differing relative measures of inputs.  Despite my improvements in the initial guess algorithm I am having a hard time getting the model to solve with different measures of inputs.  I will keep trying.  Still need to incorporate the `ppf` function to derive lower and upper bounds given some quantile.  Will try to do this tonight.

**Comment by Falter89** [comment]
Mmh, annoying that collocation is so sensitive to the measure. Alternatively I think one could also do the adjustment for relative abundance when calculating the cdfs. In the end the matching shouldn't be affect, only the scaling of the size (see my previous comment). If the collocation solver is very sensitive to the measure, maybe it makes sense to think about doing the scaling later in the code?

**Comment by Falter89** [comment]
What I mean (but I could be wrong), couldn't we simply multiply the theta we get in the version without measures by the ratio of total number of workers to firms in the economy in the data and get the correct solution? 

The idea:

sum_x( theta_unscaled(x)\* pdf_theta_unscaled(x) ) = 1  (i.e. how many workers we have which is 1 if there is no scaling)

sum_x( theta_scaled(x) \* pdf_theta_scaled(x) ) = TW (total number of workers in the economy)(pdf_theta_scaled is the number of firms that higher workers of type x)

Since there is monotonicity in the matching function is has to be true that:
sum_x (pdf_theta_unscaled (x)) = 1
sum_x (pdf_theta_scaled (x)) = TF (Total number of firms in the economy)

sum_x (theta_scaled(x)*TF *pdf_unscaled(x) = TW

Let theta_scaled(x) = M*theta_unscaled (so the scaling factor is the same for all x)

Then:
sum_x (theta_unscaled(x)_M_TF *pdf_unscaled(x) = TW

Thus: M = TW/TF

I'm not sure this makes sense. But since the measure is just a scaling factor it should be possible to add it later.

**Comment by davidrpugh** [comment]
@Falter89 

I need to think about your previous comment a bit.  Per our discussion earlier this afternoon I have implemented endogenous determination of bounds for the support of input distributions based on a user specified quantile.

Not clear to me that there is much more to do on this branch, so I will merge this branch ahead of the new release later this week.

**Pull request merged**
